#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap: COF2 PDFs, .env, SQLite schema.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

PDF_DIR="$ROOT/data/pdfs"
mkdir -p "$PDF_DIR"

declare -A COF2_PDFS=(
  ["COF2_10_Mondanites_Et_Momies_web_v1a.pdf"]="1ebOAM2Vw16T_5i9lKT4-lqmy-TdLm5DL"
  ["COF2_07_Le_Dernier_Faelys_web_v0.pdf"]="1c4u-oOBWpcy7pFybxhVIYUesyZZDehEP"
  ["COF2_Mortelle_Xelys.pdf"]="1UZAZoqKrXnco38WKpw0-p2dgrqK7DnM6"
  ["COF2_Croissez_Et_Multipliez.pdf"]="1euEHqIoSDbl2nWODq1DryAlYgsFr0e7w"
  ["COF2_Retour_En_Grace.pdf"]="16qbUJEgh0Vw8uYRJrnrcgKrA9nFI-XmM"
)

download_pdfs() {
  for filename in "${!COF2_PDFS[@]}"; do
    dest="$PDF_DIR/$filename"
    if [[ -f "$dest" ]]; then
      echo "PDF already present: $filename"
      continue
    fi
    file_id="${COF2_PDFS[$filename]}"
    echo "Downloading $filename from Google Drive ($file_id)..."
    uv run gdown "https://drive.google.com/uc?id=${file_id}" -O "$dest"
  done
}

ensure_clojure_mcp() {
  if [[ -f "${HOME}/.clojure/tools/mcp.edn" ]]; then
    echo "Clojure MCP: already installed"
    return
  fi
  echo "Installing Clojure MCP (io.github.bhauman/clojure-mcp)..."
  clojure -Ttools install-latest :lib io.github.bhauman/clojure-mcp :as mcp
  echo "Clojure MCP installed."
}

ensure_clojure() {
  if command -v clojure >/dev/null 2>&1; then
    echo "Clojure CLI: $(clojure --version)"
    return
  fi
  echo "Installing Clojure CLI..."
  if command -v sudo >/dev/null 2>&1; then
    sudo apt-get update -qq
    sudo apt-get install -y -qq rlwrap curl
  else
    apt-get update -qq
    apt-get install -y -qq rlwrap curl
  fi
  curl -fsSL https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh \
    -o /tmp/linux-install.sh
  chmod +x /tmp/linux-install.sh
  if command -v sudo >/dev/null 2>&1; then
    sudo /tmp/linux-install.sh
  else
    /tmp/linux-install.sh
  fi
  rm -f /tmp/linux-install.sh
  echo "Clojure CLI: $(clojure --version)"
}

set_env_var() {
  local key="$1"
  local value="$2"
  local env_file="$3"
  if grep -q "^${key}=" "$env_file"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$env_file"
  else
    echo "${key}=${value}" >> "$env_file"
  fi
}

setup_env_file() {
  local env_file="$ROOT/.env"
  if [[ ! -f "$env_file" ]]; then
    cp "$ROOT/.env.example" "$env_file"
  fi
  set_env_var "RPG_PDF_MOMIE" "$PDF_DIR/COF2_10_Mondanites_Et_Momies_web_v1a.pdf" "$env_file"
  set_env_var "RPG_PDF_FAELYS" "$PDF_DIR/COF2_07_Le_Dernier_Faelys_web_v0.pdf" "$env_file"
  set_env_var "NG_CLI_ANALYTICS" "false" "$env_file"
}

ensure_nvm() {
  export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
  if [[ ! -s "$NVM_DIR/nvm.sh" ]]; then
    echo "Installing nvm..."
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
  fi
  # shellcheck disable=SC1091
  . "$NVM_DIR/nvm.sh"
}

ensure_frontend_toolchain() {
  ensure_nvm
  local node_version web_bin
  node_version="$(tr -d '[:space:]' < "$ROOT/apps/web/.nvmrc")"
  echo "Installing Node ${node_version} for Angular frontend..."
  nvm install "$node_version"
  nvm alias default "$node_version" >/dev/null
  web_bin="$NVM_DIR/versions/node/v${node_version}/bin"
  export PATH="${web_bin}:$PATH"
  export NG_CLI_ANALYTICS=false
  node -v
  npm -v

  echo "Installing apps/web npm dependencies..."
  cd "$ROOT/apps/web"
  npm install --no-audit --no-fund

  echo "Pre-installing Playwright Chromium (screenshot proofs)..."
  npx playwright install chromium

  mkdir -p "$ROOT/.cursor/cache"
  cat > "$ROOT/.cursor/cache/frontend-toolchain.env" <<EOF
# Generated by cloud-agent-install.sh — sourced by dev-stack.sh
export NVM_DIR="$NVM_DIR"
export WEB_NODE_BIN_DIR="${web_bin}"
export PATH="${web_bin}:\$PATH"
export NG_CLI_ANALYTICS=false
EOF
  echo "Frontend toolchain ready."
}

ensure_port_tools() {
  if command -v lsof >/dev/null 2>&1; then
    return
  fi
  echo "Installing lsof (port cleanup for dev-stack.sh)..."
  if command -v sudo >/dev/null 2>&1; then
    sudo apt-get update -qq
    sudo apt-get install -y -qq lsof
  else
    apt-get update -qq
    apt-get install -y -qq lsof
  fi
}

ensure_clojure
ensure_clojure_mcp
ensure_port_tools
download_pdfs
setup_env_file
ensure_frontend_toolchain
cd "$ROOT"
uv run alembic upgrade head
bash "$ROOT/.cursor/scripts/seed-campaigns.sh"
echo "Cloud agent bootstrap complete."
